name: detect_new
channels:
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.3.1
  - allennlp=2.10.0
  - annotated-types=0.7.0
  - aom=3.5.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - base58=2.1.1
  - blas=1.0
  - boto3=1.35.52
  - botocore=1.35.52
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_path=1.1.6
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.16.0
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - click=8.0.4
  - colorama=0.4.6
  - commonmark=0.9.1
  - cryptography=43.0.0
  - cuda-version=11.4
  - cudatoolkit=11.4.3
  - cudnn=8.9.7.29
  - cymem=2.0.8
  - cython-blis=0.7.10
  - dataclasses=0.8
  - dav1d=1.2.1
  - dill=0.3.9
  - docker-pycreds=0.4.0
  - fairscale=0.4.6
  - ffmpeg=6.0.0
  - filelock=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - future=1.0.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gitdb=4.0.11
  - gitpython=3.1.43
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-api-core=2.22.0
  - google-auth=2.35.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.18.2
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.65.0
  - graphite2=1.3.13
  - grpc-cpp=1.48.0
  - grpcio=1.48.0
  - h2=4.1.0
  - h5py=3.11.0
  - harfbuzz=7.3.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - huggingface_hub=0.10.1
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - intel-openmp=2022.0.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jsonnet=0.20.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - langcodes=3.4.1
  - language-data=1.2.0
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libdeflate=1.17
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.9.0
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libprotobuf=3.20.3
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.49.2
  - libva=2.18.0
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.11.5
  - libzlib=1.3.1
  - magma=2.5.4
  - marisa-trie=1.2.0
  - markupsafe=2.1.5
  - mkl=2022.1.0
  - more-itertools=10.5.0
  - multidict=6.0.5
  - murmurhash=1.0.10
  - nccl=2.23.4.1
  - ncurses=6.5
  - nettle=3.9.1
  - ninja=1.12.1
  - nltk=3.9.1
  - numpy=1.24.4
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.3.2
  - p11-kit=0.24.1
  - packaging=24.1
  - pathtools=0.1.2
  - pathy=0.10.2
  - pcre2=10.44
  - pillow=9.4.0
  - pip=24.3.1
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - preshed=3.0.9
  - promise=2.3
  - proto-plus=1.25.0
  - protobuf=3.20.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=1.10.2
  - pydantic-core=2.0.2
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-lmdb=1.5.1
  - python_abi=3.8
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - re2=2022.06.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - rich=12.6.0
  - rsa=4.9
  - s3transfer=0.10.3
  - sacremoses=0.0.53
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - sentencepiece=0.1.96
  - sentry-sdk=2.16.0
  - setproctitle=1.3.3
  - setuptools=75.3.0
  - shellingham=1.5.4
  - shortuuid=1.0.13
  - six=1.16.0
  - sleef=3.7
  - smart_open=5.2.1
  - smmap=5.0.0
  - spacy=3.3.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.4.8
  - svt-av1=1.6.0
  - tensorboardx=2.6.2.2
  - termcolor=1.1.0
  - thinc=8.0.15
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.12.1
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tqdm=4.66.6
  - transformers=4.19.4
  - typer=0.4.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=1.26.19
  - wandb=0.12.21
  - wasabi=0.10.1
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /home/yyh/miniconda3/envs/detect_new
