name: new_detect
channels:
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.5.0
  - aom=3.5.0
  - attrs=24.2.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.14
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpathlib=0.20.0
  - colorama=0.4.6
  - confection=0.1.4
  - contourpy=1.1.1
  - cpython=3.8.20
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cymem=2.0.8
  - cyrus-sasl=2.1.27
  - cython-blis=0.7.10
  - dataclasses=0.8
  - dav1d=1.2.1
  - dbus=1.13.18
  - distro=1.9.0
  - emoji=2.14.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.2
  - expat=2.6.3
  - ffmpeg=4.4.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - intel-openmp=2022.0.1
  - jinja2=3.1.4
  - jiter=0.5.0
  - joblib=1.4.2
  - jpeg=9e
  - jsonlines=4.0.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - langcodes=3.4.1
  - language-data=1.2.0
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20250127.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libdrm=2.4.123
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.80.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.49.2
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - mkl=2022.1.0
  - mosec=0.8.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - murmurhash=1.0.10
  - mysql=8.4.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.1
  - nltk=3.9.1
  - numpy=1.24.4
  - openai=1.57.4
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openldap=2.6.5
  - openpyxl=3.1.5
  - openssl=3.5.1
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.0.3
  - patsy=0.5.6
  - pcre2=10.43
  - pillow=10.4.0
  - pip=24.3.1
  - pixman=0.43.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - preshed=3.0.9
  - pthread-stubs=0.4
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pyparsing=3.1.4
  - pyphen=0.10.0
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - readline=8.2
  - regex=2024.9.11
  - requests=2.32.3
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - shellingham=1.5.4
  - simplejson=3.19.3
  - sip=6.5.1
  - six=1.16.0
  - smart_open=7.0.5
  - sniffio=1.3.1
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.46.0
  - srsly=2.4.8
  - statsmodels=0.14.1
  - svt-av1=1.4.1
  - sympy=1.13.3
  - textblob=0.15.3
  - textstat=0.7.3
  - thinc=8.2.5
  - tk=8.6.14
  - toml=0.10.2
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - tornado=6.4.1
  - typer=0.4.2
  - typing_extensions=4.12.2
  - unicodedata2=15.1.0
  - wasabi=0.10.1
  - weasel=0.4.1
  - wheel=0.44.0
  - wrapt=1.16.0
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.42
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - allennlp==2.10.1
      - allennlp-models==2.10.1
      - async-timeout==4.0.3
      - base58==2.1.1
      - blis==0.7.11
      - boto3==1.35.54
      - botocore==1.35.54
      - cached-path==1.1.6
      - cachetools==5.5.0
      - commonmark==0.9.1
      - conllu==4.4.2
      - datasets==2.10.1
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - en-core-web-sm==3.3.0
      - fairscale==0.4.6
      - filelock==3.7.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - ftfy==6.2.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.22.0
      - google-auth==2.35.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.5.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.65.0
      - h5py==3.11.0
      - huggingface-hub==0.30.2
      - iniconfig==2.0.0
      - jmespath==1.0.1
      - jsonnet==0.20.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - lmdb==1.5.1
      - marisa-trie==1.2.1
      - megatron-util==1.3.2
      - modelscope==1.27.1
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.14
      - pathlib-abc==0.1.1
      - pathtools==0.1.2
      - pathy==0.11.0
      - pkgutil-resolve-name==1.3.10
      - pluggy==1.5.0
      - promise==2.3
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==3.20.3
      - psutil==6.1.0
      - py-rouge==1.1
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pygments==2.18.0
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - ray==2.10.0
      - referencing==0.35.1
      - responses==0.18.0
      - rich==12.6.0
      - rpds-py==0.20.1
      - rsa==4.9
      - s3transfer==0.10.3
      - sacremoses==0.1.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - setuptools==75.3.0
      - shortuuid==1.0.13
      - smart-open==6.4.0
      - smmap==5.0.1
      - spacy==3.3.3
      - tensorboardx==2.6.2.2
      - termcolor==1.1.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.0.2
      - torch==1.12.1
      - torchvision==0.13.1
      - tqdm==4.66.6
      - traitlets==5.14.3
      - transformers==4.46.3
      - typing-extensions==4.5.0
      - urllib3==1.26.20
      - wandb==0.12.21
      - wcwidth==0.2.13
      - word2number==1.1
      - xxhash==3.5.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/yyh/miniconda3/envs/new_detect
